name: heroes
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fpdart: ^0.0.9
  freezed_annotation: ^0.14.2
  dio: ^4.0.0
  get_it: ^7.2.0
  flutter_triple: ^1.2.3+2
  google_fonts: ^2.1.0
  
dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
  
